//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyService_Tuket.ProductionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductionService.ProductionServiceSoap")]
    public interface ProductionServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        // CODEGEN: Generating message contract since message GetAllProductsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllProducts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MyService_Tuket.ProductionService.GetAllProductsResponse GetAllProducts(MyService_Tuket.ProductionService.GetAllProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<MyService_Tuket.ProductionService.GetAllProductsResponse> GetAllProductsAsync(MyService_Tuket.ProductionService.GetAllProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductsWithCategoryName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MyService_Tuket.ProductionService.Urun[] GetProductsWithCategoryName(string KategoriAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductsWithCategoryName", ReplyAction="*")]
        System.Threading.Tasks.Task<MyService_Tuket.ProductionService.Urun[]> GetProductsWithCategoryNameAsync(string KategoriAdi);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Kullanici : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kullaniciAdiField;
        
        private string parolaField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KullaniciAdi {
            get {
                return this.kullaniciAdiField;
            }
            set {
                this.kullaniciAdiField = value;
                this.RaisePropertyChanged("KullaniciAdi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Parola {
            get {
                return this.parolaField;
            }
            set {
                this.parolaField = value;
                this.RaisePropertyChanged("Parola");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Urun : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int urunIdField;
        
        private string urunAdiField;
        
        private System.Nullable<decimal> fiyatField;
        
        private System.Nullable<short> stokField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int UrunId {
            get {
                return this.urunIdField;
            }
            set {
                this.urunIdField = value;
                this.RaisePropertyChanged("UrunId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UrunAdi {
            get {
                return this.urunAdiField;
            }
            set {
                this.urunAdiField = value;
                this.RaisePropertyChanged("UrunAdi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<decimal> Fiyat {
            get {
                return this.fiyatField;
            }
            set {
                this.fiyatField = value;
                this.RaisePropertyChanged("Fiyat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<short> Stok {
            get {
                return this.stokField;
            }
            set {
                this.stokField = value;
                this.RaisePropertyChanged("Stok");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllProducts", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllProductsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public MyService_Tuket.ProductionService.Kullanici Kullanici;
        
        public GetAllProductsRequest() {
        }
        
        public GetAllProductsRequest(MyService_Tuket.ProductionService.Kullanici Kullanici) {
            this.Kullanici = Kullanici;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllProductsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public MyService_Tuket.ProductionService.Urun[] GetAllProductsResult;
        
        public GetAllProductsResponse() {
        }
        
        public GetAllProductsResponse(MyService_Tuket.ProductionService.Urun[] GetAllProductsResult) {
            this.GetAllProductsResult = GetAllProductsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductionServiceSoapChannel : MyService_Tuket.ProductionService.ProductionServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductionServiceSoapClient : System.ServiceModel.ClientBase<MyService_Tuket.ProductionService.ProductionServiceSoap>, MyService_Tuket.ProductionService.ProductionServiceSoap {
        
        public ProductionServiceSoapClient() {
        }
        
        public ProductionServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductionServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductionServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductionServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyService_Tuket.ProductionService.GetAllProductsResponse MyService_Tuket.ProductionService.ProductionServiceSoap.GetAllProducts(MyService_Tuket.ProductionService.GetAllProductsRequest request) {
            return base.Channel.GetAllProducts(request);
        }
        
        public MyService_Tuket.ProductionService.Urun[] GetAllProducts(MyService_Tuket.ProductionService.Kullanici Kullanici) {
            MyService_Tuket.ProductionService.GetAllProductsRequest inValue = new MyService_Tuket.ProductionService.GetAllProductsRequest();
            inValue.Kullanici = Kullanici;
            MyService_Tuket.ProductionService.GetAllProductsResponse retVal = ((MyService_Tuket.ProductionService.ProductionServiceSoap)(this)).GetAllProducts(inValue);
            return retVal.GetAllProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyService_Tuket.ProductionService.GetAllProductsResponse> MyService_Tuket.ProductionService.ProductionServiceSoap.GetAllProductsAsync(MyService_Tuket.ProductionService.GetAllProductsRequest request) {
            return base.Channel.GetAllProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyService_Tuket.ProductionService.GetAllProductsResponse> GetAllProductsAsync(MyService_Tuket.ProductionService.Kullanici Kullanici) {
            MyService_Tuket.ProductionService.GetAllProductsRequest inValue = new MyService_Tuket.ProductionService.GetAllProductsRequest();
            inValue.Kullanici = Kullanici;
            return ((MyService_Tuket.ProductionService.ProductionServiceSoap)(this)).GetAllProductsAsync(inValue);
        }
        
        public MyService_Tuket.ProductionService.Urun[] GetProductsWithCategoryName(string KategoriAdi) {
            return base.Channel.GetProductsWithCategoryName(KategoriAdi);
        }
        
        public System.Threading.Tasks.Task<MyService_Tuket.ProductionService.Urun[]> GetProductsWithCategoryNameAsync(string KategoriAdi) {
            return base.Channel.GetProductsWithCategoryNameAsync(KategoriAdi);
        }
    }
}
